/**
 * iconMap — bảng map **glyph Material Symbols → component lucide** (nguồn sự thật:
 * `docs/design/icon-map.md`). Dùng qua `<Icon name="check_circle" size={18} />`
 * (`src/frontend/ui/Icon.tsx`), KHÔNG import trực tiếp bảng này trong view.
 *
 * VÌ SAO LÀ MAP THEO CHUỖI (deviation có chủ ý so với `docs/plans/07-execution-phases.md` §7):
 *   `07` §7 yêu cầu đổi field `.icon` trong data thành **tham chiếu component**. Không làm
 *   vậy được: các object trong `src/data/mockData.ts` và `src/stores/useProductionStore.ts`
 *   được seed xuống Supabase (`seedService`) và nằm trong store — **tham chiếu component
 *   không serialize được**. Nên field `.icon` GIỮ NGUYÊN kiểu `string`, và mọi điểm render
 *   đi qua `<Icon name={...} />`. Không sót icon nào vì tất cả đều qua map này.
 *
 * 5 glyph không có tương đương trực tiếp trong lucide 0.546 (`add_shopping_cart`,
 * `remove_shopping_cart`, `cloud_sync`, `lock_reset`, `square_foot`) được **ghép** bằng
 * `createLucideIcon` — xem khối COMPOSED bên dưới. Ghép bằng icon-node (không bọc `<span>`)
 * nên vẫn là MỘT `<svg>` 24×24, không đổi layout so với icon thường.
 *
 * KHÔNG sửa tay bảng dưới đây lệch khỏi `docs/design/icon-map.md`; thêm glyph mới thì
 * thêm cả hai nơi.
 */

import {
  AlignHorizontalSpaceAround,
  Aperture,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpToLine,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  BellRing,
  Blend,
  Bookmark,
  Bot,
  Box,
  Building,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartColumn,
  ChartGantt,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Code,
  Coins,
  Compass,
  Construction,
  Copy,
  Cpu,
  Download,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileBadge,
  FilePen,
  FileText,
  FileUp,
  Flame,
  FlaskConical,
  Focus,
  FolderArchive,
  FolderOpen,
  FolderX,
  Funnel,
  GalleryHorizontal,
  Gauge,
  Globe,
  Grid3x3,
  Hammer,
  Hand,
  Handshake,
  HardHat,
  Headset,
  Hexagon,
  Hourglass,
  House,
  IdCard,
  Image,
  Images,
  Inbox,
  Info,
  Key,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MapPinHouse,
  Maximize,
  Megaphone,
  Menu,
  MessageCircle,
  Minimize,
  Monitor,
  MousePointerClick,
  Move3d,
  Network,
  Package,
  PackageX,
  PaintBucket,
  PaintRoller,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Pencil,
  Percent,
  Phone,
  Pipette,
  Plane,
  Plus,
  Pointer,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  ReceiptText,
  RefreshCw,
  Rocket,
  Rotate3d,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Save,
  Scaling,
  Scan,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings,
  Shapes,
  Share2,
  Shield,
  ShieldCheck,
  ShieldUser,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  SlidersHorizontal,
  Smartphone,
  Sparkle,
  Sparkles,
  Split,
  SprayCan,
  Square,
  SquareCheck,
  SquareDashedMousePointer,
  SquareKanban,
  Store,
  Table,
  Tag,
  Thermometer,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Type,
  Unlink,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  WandSparkles,
  Warehouse,
  Waypoints,
  Workflow,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import { createLucideIcon, type IconNode, type LucideIcon } from 'lucide-react';

/** Glyph lạ (chưa có trong bảng) → icon này + `console.warn` ở DEV (xem `Icon.tsx`). */
export const FALLBACK_ICON: LucideIcon = CircleQuestionMark;

/* ---------------------------------------------------------------------------
   COMPOSED — 5 glyph Material Symbols không có tương đương trực tiếp trong lucide 0.546.
   Cùng viewBox 24×24, cùng `stroke="currentColor"`, cùng `strokeWidth` mặc định.
   --------------------------------------------------------------------------- */

const round2 = (n: number) => Math.round(n * 100) / 100;

/**
 * Huy hiệu mũi tên tròn NGƯỢC chiều kim đồng hồ: lấy đúng hình lucide `RefreshCcw`
 * (tâm 12,12 bán kính 9) rồi thu nhỏ quanh tâm `(cx,cy)` về bán kính `r`.
 */
function ccwBadge(cx: number, cy: number, r: number): IconNode {
  const k = r / 9;
  const px = (x: number) => round2(cx + (x - 12) * k);
  const py = (y: number) => round2(cy + (y - 12) * k);
  return [
    ['path', { d: `M${px(3)} ${py(12)}a${r} ${r} 0 1 0 ${r} ${-r}` }],
    [
      'path',
      {
        d: `M${px(12)} ${py(3)}a${round2(r * 1.0833)} ${round2(r * 1.0833)} 0 0 0 ${round2(-r * 0.7489)} ${round2(r * 0.3044)}L${px(3)} ${py(8)}`,
      },
    ],
    ['path', { d: `M${px(3)} ${py(3)}v${round2(r * 0.5556)}h${round2(r * 0.5556)}` }],
  ];
}

/** `ShoppingCart` (lucide) — dùng lại nguyên hình cho 2 glyph ghép bên dưới. */
const CART_NODES: IconNode = [
  ['circle', { cx: '8', cy: '21', r: '1' }],
  ['circle', { cx: '19', cy: '21', r: '1' }],
  [
    'path',
    { d: 'M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12' },
  ],
];

/** `add_shopping_cart` = giỏ hàng + dấu `+` ở góc trên phải. */
const AddShoppingCart: LucideIcon = createLucideIcon('add-shopping-cart', [
  ...CART_NODES,
  ['path', { d: 'M16.5 4h5' }],
  ['path', { d: 'M19 1.5v5' }],
]);

/** `remove_shopping_cart` = giỏ hàng + dấu `x` ở góc trên phải (trạng thái giỏ rỗng). */
const RemoveShoppingCart: LucideIcon = createLucideIcon('remove-shopping-cart', [
  ...CART_NODES,
  ['path', { d: 'M16.6 1.6l4.8 4.8' }],
  ['path', { d: 'M21.4 1.6l-4.8 4.8' }],
]);

/** `cloud_sync` = đám mây + mũi tên tròn ngược chiều ở góc dưới phải. */
const CloudSync: LucideIcon = createLucideIcon('cloud-sync', [
  ['path', { d: 'M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z' }],
  ...ccwBadge(19.2, 19.2, 2.8),
]);

/** `lock_reset` = ổ khoá (thu nhỏ 0.78) + mũi tên tròn ngược chiều (đặt lại mật khẩu). */
const LockReset: LucideIcon = createLucideIcon('lock-reset', [
  ['rect', { width: '14', height: '8.6', x: '2.4', y: '8.6', rx: '1.6', ry: '1.6' }],
  ['path', { d: 'M5.5 8.6V5.5a3.9 3.9 0 0 1 7.8 0v3.1' }],
  ...ccwBadge(18.5, 18, 3.3),
]);

/** `square_foot` = hình vuông + đường chéo + 2 đầu mũi tên kích thước (diện tích/khổ). */
const SquareFoot: LucideIcon = createLucideIcon('square-foot', [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M20.4 3.6 3.6 20.4' }],
  ['path', { d: 'M17.2 3.6H20.4v3.2' }],
  ['path', { d: 'M3.6 16.8v3.6h3.2' }],
]);

/* ---------------------------------------------------------------------------
   Bảng map. Khoá = tên glyph Material Symbols (giữ nguyên chuỗi trong data).
   --------------------------------------------------------------------------- */

export const iconMap: Record<string, LucideIcon> = {
  '360': RotateCw,
  '3d_rotation': Rotate3d,
  'account_balance': Landmark,
  'account_balance_wallet': Wallet,
  'account_circle': CircleUser,
  'account_tree': Network,
  'add': Plus,
  'add_business': Store,
  'add_circle': CirclePlus,
  'admin_panel_settings': ShieldUser,
  'ads_click': MousePointerClick,
  'analytics': ChartLine,
  'apartment': Building,
  'arrow_back': ArrowLeft,
  'arrow_downward': ArrowDown,
  'arrow_drop_down': ChevronDown,
  'arrow_drop_up': ChevronUp,
  'arrow_forward': ArrowRight,
  'arrow_upward': ArrowUp,
  'attachment': Paperclip,
  'auto_awesome': Sparkles,
  'auto_fix_high': WandSparkles,
  'badge': IdCard,
  'bar_chart': ChartColumn,
  'bolt': Zap,
  'bookmark': Bookmark,
  'bookmark_border': Bookmark,
  'build': Wrench,
  'calculate': Calculator,
  'call': Phone,
  'call_split': Split,
  'campaign': Megaphone,
  'cancel': CircleX,
  'category': Shapes,
  'celebration': PartyPopper,
  'center_focus_strong': Focus,
  'chat': MessageCircle,
  'check': Check,
  'check_box': SquareCheck,
  'check_box_outline_blank': Square,
  'check_circle': CircleCheck,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'cleaning_services': SprayCan,
  'close': X,
  'cloud_upload': CloudUpload,
  'code': Code,
  'colorize': Pipette,
  'compare_arrows': ArrowLeftRight,
  'confirmation_number': Ticket,
  'construction': Construction,
  'content_copy': Copy,
  'corporate_fare': Building,
  'crop_square': Square,
  'dashboard': LayoutDashboard,
  'delete': Trash2,
  'deployed_code': Box,
  'description': FileText,
  'design_services': PenTool,
  'desktop_windows': Monitor,
  'developer_board': CircuitBoard,
  'domain': Building2,
  'done': Check,
  'download': Download,
  'drag_pan': Hand,
  'draw': PenTool,
  'edit': Pencil,
  'edit_note': FilePen,
  'engineering': HardHat,
  'error': CircleAlert,
  'event': Calendar,
  'expand_more': ChevronDown,
  'explore': Compass,
  'extension': Puzzle,
  'fact_check': ClipboardCheck,
  'factory': Factory,
  'filter_alt': Funnel,
  'filter_center_focus': Scan,
  'fit_screen': Scaling,
  'flare': Sparkle,
  'flight': Plane,
  'folder_off': FolderX,
  'folder_open': FolderOpen,
  'folder_zip': FolderArchive,
  'format_color_fill': PaintBucket,
  'format_list_bulleted': List,
  'format_paint': PaintRoller,
  'fullscreen': Maximize,
  'fullscreen_exit': Minimize,
  'functions': Sigma,
  'grid_3x3': Grid3x3,
  'grid_4x4': Grid3x3,
  'grid_view': LayoutGrid,
  'group': Users,
  'handshake': Handshake,
  'handyman': Wrench,
  'help': CircleQuestionMark,
  'hexagon': Hexagon,
  'home': House,
  'home_pin': MapPinHouse,
  'home_repair_service': Hammer,
  'home_work': Building2,
  'horizontal_distribute': AlignHorizontalSpaceAround,
  'hourglass_empty': Hourglass,
  'hourglass_top': Hourglass,
  'hub': Waypoints,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'inventory': Package,
  'inventory_2': Package,
  'join_inner': Blend,
  'key': Key,
  'layers': Layers,
  'lens_blur': Aperture,
  'license': FileBadge,
  'lightbulb': Lightbulb,
  'linear_scale': SlidersHorizontal,
  'link': Link,
  'link_off': Unlink,
  'local_fire_department': Flame,
  'local_shipping': Truck,
  'location_on': MapPin,
  'lock': Lock,
  'login': LogIn,
  'logout': LogOut,
  'mail': Mail,
  'manage_accounts': UserCog,
  'memory': Cpu,
  'menu': Menu,
  'navigate_next': ChevronRight,
  'notifications_active': BellRing,
  'open_in_full': Expand,
  'open_in_new': ExternalLink,
  'palette': Palette,
  'payments': Banknote,
  'pending_actions': ClipboardList,
  'percent': Percent,
  'person': User,
  'person_add': UserPlus,
  'photo_camera': Camera,
  'photo_library': Images,
  'pie_chart': ChartPie,
  'pin_drop': MapPin,
  'policy': ScrollText,
  'precision_manufacturing': Factory,
  'preview': Eye,
  'price_check': BadgeDollarSign,
  'print': Printer,
  'production_quantity_limits': PackageX,
  'progress_activity': LoaderCircle,
  'qr_code_2': QrCode,
  'query_stats': ChartLine,
  'receipt_long': ReceiptText,
  'refresh': RefreshCw,
  'replay': RotateCcw,
  'request_quote': FileText,
  'restart_alt': RotateCcw,
  'rocket_launch': Rocket,
  'rotate_right': RotateCw,
  'route': Route,
  'save': Save,
  'schedule': Clock,
  'schema': Workflow,
  'science': FlaskConical,
  'search': Search,
  'search_off': SearchX,
  'security': ShieldCheck,
  'select_all': SquareDashedMousePointer,
  'sell': Tag,
  'send': Send,
  'sensors': Radio,
  'settings': Settings,
  'share': Share2,
  'share_location': MapPin,
  'shelves': Warehouse,
  'shield': Shield,
  'shield_person': ShieldUser,
  'shopping_bag': ShoppingBag,
  'shopping_cart': ShoppingCart,
  'smart_toy': Bot,
  'smartphone': Smartphone,
  'speed': Gauge,
  'store': Store,
  'storefront': Store,
  'straighten': Ruler,
  'support_agent': Headset,
  'swap_horiz': ArrowLeftRight,
  'sync': RefreshCw,
  'table_rows': Table,
  'tag': Tag,
  'thermostat': Thermometer,
  'timer': Timer,
  'title': Type,
  'token': Coins,
  'touch_app': Pointer,
  'transform': Move3d,
  'travel_explore': Globe,
  'trending_up': TrendingUp,
  'tune': SlidersHorizontal,
  'upload_file': FileUp,
  'verified': BadgeCheck,
  'verified_user': ShieldCheck,
  'vertical_align_bottom': ArrowDownToLine,
  'vertical_align_top': ArrowUpToLine,
  'view_carousel': GalleryHorizontal,
  'view_in_ar': Box,
  'view_kanban': SquareKanban,
  'view_list': List,
  'view_timeline': ChartGantt,
  'visibility': Eye,
  'visibility_off': EyeOff,
  'warehouse': Warehouse,
  'warning': TriangleAlert,
  'wb_incandescent': Lightbulb,

  /* 5 glyph ghép — xem khối COMPOSED ở trên. */
  add_shopping_cart: AddShoppingCart,
  remove_shopping_cart: RemoveShoppingCart,
  cloud_sync: CloudSync,
  lock_reset: LockReset,
  square_foot: SquareFoot,
};
